// This file was generated by Prisma, and assumes you have installed the following:
// rm -rf node_modules package-lock.json
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"]!,
    // url: process.env["DATABASE_URL"]!,
  },
});
